### ISSUE TITLE
Combine initial image and prompt semantically in generated images

### ISSUE THREAD

**Issue by AkashKaranam** [RiceComp413-Fall2022/Stickr#60]
Currently the init_image and prompt_strength fields in the stable-diffusion model on replicate combine the initial image and prompt stylistically but not semantically. i.e if I start with a base image of an owl and have a prompt "engineering hat" it will create an engineering hat with the same color pattern as the initial owl image. However, we want it to add an engineering hat to the owl.

**Comment by bthomas44** [comment]
After doing some experimentation with Stable Diffusion and research on other models, I don't think this is feasible. The closest approximation we could achieve is to use the captions of any preset images we provide. For user uploads, we can ask the user to create a 'comprehensive' query that encapsulates the upload. (i.e. If they upload their own owl image, the prompt submitted would still have to be "owl wearing an engineering hat", not just "wearing a hat")
