### ISSUE TITLE
When user clicks on an image make it full screen in an editing view

### ISSUE THREAD

**Issue by AkashKaranam** [RiceComp413-Fall2022/Stickr#62]
In our demo version we will have four images in the search results. We want a user to be able to pick the one they like the most and when they click on the image it should open up in a full screen mode that has some editing capability (adding text onto the generated sticker)

**Comment by bthomas44** [comment]
[Custom ink](https://www.customink.com/ndx/?PK=379813&SK=379800&prefer_singles=false#/) is a good example of a simple sticker editing framework.

**Comment by ayushsachdeva1** [comment]
Completed.
