### ISSUE TITLE
Have the image only be the sticker

### ISSUE THREAD

**Issue by AkashKaranam** [RiceComp413-Fall2022/Stickr#63]
Currently many of the generated images are pictures of a sticker on a table or some other surface. Ideally the image is only the sticker with a black background or something like that. I am not sure how exactly to fix this issue. Perhaps there is some image segmentation we have to do or we can change the prompt engineering to only produce the sticker.

**Comment by bthomas44** [comment]
One approach is in the prompt engineering phase. Can append text (e.g. ", png image outline") to the prompt. If we are limiting the output shape to a select few options, we can again change the input to guide the model (e.g. "circular image of"). Lets to model do a lot of the grunt work, but have to be careful of how the prompt engineering may unintentionally deviate from the user's desired image. 

After the generation completes, we can allow the user to select the desired 'cutout' of their sticker. Stretch work can be done to implement automatic outline detection.

**Comment by ayushsachdeva1** [comment]
Cropping takes care of this issue.
